apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::476177315876:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-w4jqrB2KKFVQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::476177315876:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-20T14:43:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1326"
  uid: 0128a5a2-ae5e-4dc3-9715-861a848b4381
